# Generated by Django 5.1.6 on 2025-02-25 13:04

import django.core.validators
import django.db.models.deletion
import hr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedulings',
            fields=[
                ('slot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('students', models.FileField(upload_to=hr.models.Schedulings.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('subject', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Django', 'Django'), ('Spring', 'Spring'), ('Hibernet', 'Hibernet'), ('SQL', 'SQL'), ('Web-Technology', 'Web-Technology'), ('React JS', 'React JS'), ('MongoDB', 'MongoDB'), ('Express JS', 'Express JS')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
