# Generated by Django 5.1.6 on 2025-02-17 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.CharField(max_length=50)),
                ('add', models.TextField()),
                ('course', models.CharField(choices=[('Python Fullstack Development', 'Python Fullstack Development'), ('Java Fullstack Development', 'Java Fullstack Development'), ('MERN Fullstack Development', 'MERN Fullstack Development'), ('Fullstack Testing', 'Fullstack Testing')], max_length=50)),
                ('profile_pic', models.ImageField(upload_to='students_profiles/')),
                ('resume', models.FileField(upload_to='students_resumes/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
