# Generated by Django 5.1.6 on 2025-02-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(choices=[('Python Fullstack Development', 'Python Fullstack Development'), ('Java Fullstack Development', 'Java Fullstack Development'), ('MERN Fullstack Development', 'MERN Fullstack Development'), ('Fullstack Testing', 'Fullstack Testing')], default='Python Fullstack Development', max_length=50),
        ),
    ]
