# Generated by Django 5.1.6 on 2025-02-25 12:49

import django.core.validators
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentprofile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, choices=[('Python Fullstack Development', 'Python Fullstack Development'), ('Java Fullstack Development', 'Java Fullstack Development'), ('MERN Fullstack Development', 'MERN Fullstack Development'), ('Fullstack Testing', 'Fullstack Testing')], default='Python Fullstack Development', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='students_profiles/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(upload_to=student.models.StudentProfile.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])]),
        ),
    ]
